[lint]
select = [
    "D", # pydocstyle
]
ignore = [
    # Undocumented code
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",

    # Conflicting pydocstyle rules
    "D203",
    "D212",
]
