#!/usr/bin/env python

from rosbridge_server.rosbridge_websocket import RosbridgeWebSocket
from signal import signal, SIGINT, SIG_DFL
from tornado.ioloop import IOLoop
from tornado.web import Application
import sys

signal(SIGINT, SIG_DFL)

port = get_param('/rosbridge/port', 9090)
if "--port" in sys.argv:
    idx = sys.argv.index("--port") + 1
    if idx < len(sys.argv):
        port = int(sys.argv[idx])
    else:
        print "--port argument provided without a value."
        sys.exit(-1)

application = Application([(r"/", RosbridgeWebSocket), (r"", RosbridgeWebSocket)])
application.listen(port)
loginfo("Rosbridge server started on port %d", port)

IOLoop.instance().start()

