# The client ID returned from the authentication request for the client connection
string client_connection_id

# The optional 'id' field in rosbridge  protocol
string id

# The 'op' field in the rosbridge protocol
string ros_operation_type

# For pub/sub this is the topic name. For services this is the service name.
string ros_operation_name_arg

---

bool authorized