name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - uses: pre-commit/action@v3.0.1

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Test supported ROS 2 distributions
          # https://docs.ros.org/en/rolling/Releases.html
          # NOTE: Humble and Jazzy do not work on the `ros2` branch, so they are tested in their own branches.
          - ros: kilted
            container: ubuntu:noble
          - ros: rolling
            container: ubuntu:noble

    name: ROS 2 ${{ matrix.ros }} (${{ matrix.container }})
    runs-on: ubuntu-24.04
    # container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v6
        with:
          path: ros_ws/src

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 3.28.3

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - uses: ros-tooling/setup-ros@v0.7

      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: ${{ matrix.ros }}

      - name: Show environment
        if: ${{ always() }}
        run: |
          echo -e "\e[35;1msource /opt/ros/${{ matrix.ros }}/setup.bash\e[0m"
          source /opt/ros/${{ matrix.ros }}/setup.bash
          echo -e "\e[35;1mecho -e "printenv | sort\e[0m"
          echo -e "printenv | sort
          echo -e "\e[35;1mwhich pip3\e[0m"
          which pip3
          echo -e "\e[35;1mpip3 freeze\e[0m"
          pip3 freeze
          echo -e "\e[35;1mwhich python3\e[0m"
          which python3
          echo -e "\e[35;1mpython3 -c \"import sys;print(sys.path)\"\e[0m"
          python3 -c "import sys;print(sys.path)"
          echo -e "\e[35;1mpython3 -c \"import ament_package;print(ament_package.__file__)\"\e[0m"
          python3 -c "import ament_package;print(ament_package.__file__)"
          echo -e "\e[35;1mpython3 -c "from ament_package.templates import get_environment_hook_template_path;print('done')"\e[0m"
          python3 -c "from ament_package.templates import get_environment_hook_template_path;print('done')"
          echo -e "\e[35;1mwhich cmake\e[0m"
          which cmake
          echo -e "\e[35;1mcmake --version\e[0m"
          cmake --version
