name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip
      - run: pip install bandit codespell flake8
      - run: bandit --recursive --skip B101,B110,B311 .
      - run: codespell --ignore-words-list=miror
      - run: flake8 . --count --max-complexity=36 --max-line-length=228
                      --select=E5,E9,F63,F7 --show-source --statistics  # ,F82
      # Undefined names need to be fixed (#593,#604) and the --exit-zero removed.
      - run: flake8 . --count --exit-zero --select=F82 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88
                      --show-source --statistics
