name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip
      - run: pip install bandit codespell flake8
      - run: bandit --recursive --skip B101,B110,B311 .
      # See setup.cfg for the default settings for codespell and flake8
      - run: codespell
      - run: flake8
      # Undefined names need to be fixed (#604) and the --exit-zero removed.
      - run: flake8 . --count --exit-zero --select=F82 --show-source --statistics
